/** @implements SPEC-ORBIS-P0-ACTIONS */
export type ActionId =
  | 'page.back'
  | 'page.forward'
  | 'page.reload'
  | 'page.new'
  | 'page.close'
  | 'cura.new'
  | 'fenestra.alwaysOnTop.toggle'
  | 'fenestra.minimizeOthers'
  | 'fenestra.minimize'
  | 'fenestra.maximize.toggle'
  | 'fenestra.opacity.cycle'
  | 'indagatio.open'
  | 'nexus.layout.toggle'
  | 'habitus.set:desktop'
  | 'habitus.set:mobile'
  | 'habitus.set:shopping'
  | 'comparatio.toggle'
  | 'habitus.cycle'
  | 'rota.open'
